version: '2.0'
services:
    fc:
        build: .
        ports:
            - "3030:3030"
        environment:
            - VIRTUAL_HOST=findclancy.com
        links:
            - database
        depends_on:
            - database
    database:
        image: mongo
        ports:
            - 27017:27017
        restart: always

networks:
    default:
        external:
            name: everything
