version: '2.0'
services:
    front-end:
        build: .
        ports:
            - "3000:3000"
        environment:
            - VIRTUAL_HOST=easymoveplanner.com
        links:
            - database
        depends_on:
            - database
    database:
        image: mongo
        ports:
            - 27017:27017
        restart: always
        environment:
            - VIRTUAL_HOST=easymoveplanner.com